rest(1.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(1.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.125, bpm)
keypress("o", x, bpm)
rest(2.875, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
rest(0.125, bpm)
keypress("s", x, bpm)
rest(0.375, bpm)
keypress("Y", x, bpm)
rest(0.125, bpm)
keypress("s", x, bpm)
rest(0.375, bpm)
keypress("i", x, bpm)
rest(0.125, bpm)
keypress("d", x, bpm)
rest(0.125, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.125, bpm)
keypress("o", x, bpm)
rest(3.375, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.125, bpm)
keypress("E", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
rest(0.125, bpm)
keypress("P", x, bpm)
rest(0.125, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.125, bpm)
keypress("r", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
rest(0.125, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.125, bpm)
keypress("u", x, bpm)
rest(0.125, bpm)
keypress("O", x, bpm)
rest(0.125, bpm)
keypress("a", x, bpm)
rest(1.125, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.125, bpm)
keypress("s", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
rest(0.125, bpm)
keypress("j", x, bpm)
rest(0.375, bpm)
keypress("u", x, bpm)
rest(0.125, bpm)
keypress("j", x, bpm)
rest(0.375, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("h", x, bpm)
rest(0.375, bpm)
keypress("p", x, bpm)
rest(0.125, bpm)
keypress("h", x, bpm)
rest(0.375, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.125, bpm)
keypress("d", x, bpm)
rest(0.125, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.125, bpm)
keypress("d", x, bpm)
rest(0.125, bpm)
keypress("f", x, bpm)
rest(1.25, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
rest(0.125, bpm)
keypress("h", x, bpm)
rest(0.375, bpm)
keypress("i", x, bpm)
rest(0.125, bpm)
keypress("h", x, bpm)
rest(0.375, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("g", x, bpm)
rest(0.375, bpm)
keypress("g", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.125, bpm)
keypress("s", x, bpm)
rest(0.125, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.125, bpm)
keypress("s", x, bpm)
rest(0.125, bpm)
keypress("d", x, bpm)
rest(3.25, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("a", x, bpm)
rest(0.125, bpm)
keypress("f", x, bpm)
rest(1.25, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.125, bpm)
keypress("o", x, bpm)
rest(0.375, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
rest(0.125, bpm)
keypress("s", x, bpm)
rest(0.375, bpm)
keypress("Y", x, bpm)
rest(0.125, bpm)
keypress("s", x, bpm)
rest(0.375, bpm)
keypress("i", x, bpm)
rest(0.125, bpm)
keypress("d", x, bpm)
rest(0.375, bpm)
keypress("O", x, bpm)
rest(0.125, bpm)
keypress("d", x, bpm)
rest(0.375, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.125, bpm)
keypress("f", x, bpm)
rest(0.375, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.125, bpm)
keypress("d", x, bpm)
rest(0.125, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.125, bpm)
keypress("d", x, bpm)
rest(0.125, bpm)
keypress("h", x, bpm)
rest(1.75, bpm)
keypress("i", x, bpm)
rest(0.125, bpm)
keypress("s", x, bpm)
rest(0.375, bpm)
keypress("j", x, bpm)
rest(0.125, bpm)
keypress("l", x, bpm)
rest(0.375, bpm)
keypress("j", x, bpm)
rest(0.125, bpm)
keypress("l", x, bpm)
rest(0.375, bpm)
keypress("h", x, bpm)
rest(0.125, bpm)
keypress("k", x, bpm)
rest(0.375, bpm)
keypress("h", x, bpm)
rest(0.125, bpm)
keypress("k", x, bpm)
rest(0.375, bpm)
keypress("g", x, bpm)
rest(0.125, bpm)
keypress("j", x, bpm)
rest(0.375, bpm)
keypress("g", x, bpm)
rest(0.125, bpm)
keypress("j", x, bpm)
rest(0.375, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.125, bpm)
keypress("h", x, bpm)
rest(0.375, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.125, bpm)
keypress("f", x, bpm)
rest(0.375, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.125, bpm)
keypress("s", x, bpm)
rest(2.375, bpm)
keypress("y", x, bpm)
rest(0.125, bpm)
keypress("s", x, bpm)
rest(0.375, bpm)
keypress("i", x, bpm)
rest(0.125, bpm)
keypress("s", x, bpm)
rest(0.375, bpm)
keypress("O", x, bpm)
rest(0.125, bpm)
keypress("D", x, bpm)
rest(0.375, bpm)
keypress("s", x, bpm)
rest(0.125, bpm)
keypress("D", x, bpm)
rest(0.375, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.125, bpm)
keypress("h", x, bpm)
rest(0.125, bpm)
keypress("l", x, bpm)
rest(3.75, bpm)
keypress("D", x, bpm)
rest(0.125, bpm)
keypress("h", x, bpm)
rest(0.125, bpm)
keypress("l", x, bpm)
rest(0.75, bpm)
keypress("g", x, bpm)
rest(0.125, bpm)
keypress("H", x, bpm)
rest(0.125, bpm)
keypress("l", x, bpm)
rest(0.75, bpm)
keypress("d", x, bpm)
rest(0.125, bpm)
keypress("g", x, bpm)
rest(0.125, bpm)
keypress("l", x, bpm)
rest(0.75, bpm)
keypress("s", x, bpm)
rest(0.125, bpm)
keypress("f", x, bpm)
rest(0.125, bpm)
keypress("l", x, bpm)

finishedSong()
