rest(2.292, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("9", x, bpm)
rest(6.593, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
rest(4.546, bpm)
keypress("p", x, bpm)
rest(0.509, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.528, bpm)
keypress("s", x, bpm)
rest(1.491, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.509, bpm)
keypress("p", x, bpm)
rest(0.509, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.509, bpm)
keypress("p", x, bpm)
rest(0.509, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
rest(1.537, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.509, bpm)
keypress("u", x, bpm)
rest(1.009, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("9", x, bpm)
rest(0.509, bpm)
keypress("u", x, bpm)
rest(0.509, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("9", x, bpm)
rest(0.509, bpm)
keypress("u", x, bpm)
rest(1.009, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
rest(1.519, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
rest(0.509, bpm)
keypress("a", x, bpm)
rest(1.009, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("9", x, bpm)
rest(0.255, bpm)
keypress("u", x, bpm)
rest(0.255, bpm)
keypress("u", x, bpm)
rest(0.509, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("9", x, bpm)
rest(0.509, bpm)
keypress("a", x, bpm)
rest(1.009, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("6", x, bpm)
rest(1.519, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(0.509, bpm)
keypress("u", x, bpm)
rest(1.019, bpm)
keypress("u", x, bpm)
rest(0.255, bpm)
keypress("u", x, bpm)
rest(0.255, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
rest(0.509, bpm)
keypress("a", x, bpm)
rest(1.019, bpm)
keypress("a", x, bpm)
rest(0.509, bpm)
keypress("a", x, bpm)
keypress("6", x, bpm)
rest(1.255, bpm)
keypress("p", x, bpm)
rest(0.509, bpm)
keypress("p", x, bpm)
rest(0.255, bpm)
keypress("a", x, bpm)
keypress("6", x, bpm)
rest(1.255, bpm)
keypress("p", x, bpm)
rest(0.255, bpm)
keypress("p", x, bpm)
rest(0.509, bpm)
keypress("a", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("9", x, bpm)
rest(0.509, bpm)
keypress("p", x, bpm)
rest(0.509, bpm)
keypress("a", x, bpm)
keypress("9", x, bpm)
rest(0.509, bpm)
keypress("p", x, bpm)
rest(0.509, bpm)
keypress("y", x, bpm)
rest(0.255, bpm)
keypress("y", x, bpm)
rest(0.255, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(0.491, bpm)
keypress("s", x, bpm)
rest(1.019, bpm)
keypress("a", x, bpm)
rest(0.509, bpm)
keypress("p", x, bpm)
rest(0.509, bpm)
keypress("o", x, bpm)
rest(0.509, bpm)
keypress("a", x, bpm)
rest(0.509, bpm)
keypress("s", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("9", x, bpm)
rest(0.509, bpm)
keypress("y", x, bpm)
rest(0.509, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.509, bpm)
keypress("d", x, bpm)
rest(0.509, bpm)
keypress("s", x, bpm)
rest(1.019, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.509, bpm)
keypress("a", x, bpm)
rest(0.509, bpm)
keypress("s", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("9", x, bpm)
rest(0.509, bpm)
keypress("u", x, bpm)
rest(0.255, bpm)
keypress("y", x, bpm)
rest(0.255, bpm)
keypress("y", x, bpm)
rest(0.509, bpm)
keypress("p", x, bpm)
rest(0.509, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.509, bpm)
keypress("p", x, bpm)
rest(0.255, bpm)
keypress("p", x, bpm)
rest(0.255, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(1.264, bpm)
keypress("r", x, bpm)
rest(0.255, bpm)
keypress("I", x, bpm)
keypress("0", x, bpm)
rest(0.255, bpm)
keypress("I", x, bpm)
rest(0.255, bpm)
keypress("I", x, bpm)
rest(0.255, bpm)
keypress("I", x, bpm)
rest(0.255, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.519, bpm)
keypress("y", x, bpm)
rest(1.5, bpm)
keypress("6", x, bpm)
rest(0.509, bpm)
keypress("d", x, bpm)
rest(0.509, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
rest(0.509, bpm)
keypress("p", x, bpm)
rest(1.009, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("9", x, bpm)
rest(0.255, bpm)
keypress("p", x, bpm)
rest(0.255, bpm)
keypress("a", x, bpm)
rest(0.509, bpm)
keypress("a", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("9", x, bpm)
rest(2.019, bpm)
keypress("a", x, bpm)
keypress("8", x, bpm)
rest(0.509, bpm)
keypress("d", x, bpm)
rest(0.509, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.509, bpm)
keypress("o", x, bpm)
rest(0.509, bpm)
keypress("o", x, bpm)
rest(0.509, bpm)
keypress("p", x, bpm)
rest(0.509, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.509, bpm)
keypress("a", x, bpm)
rest(0.509, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("0", x, bpm)
rest(0.255, bpm)
keypress("p", x, bpm)
rest(0.255, bpm)
keypress("a", x, bpm)
rest(1.019, bpm)
keypress("O", x, bpm)
rest(0.255, bpm)
keypress("p", x, bpm)
rest(0.255, bpm)
keypress("a", x, bpm)
rest(1.019, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.509, bpm)
keypress("f", x, bpm)
rest(0.509, bpm)
keypress("d", x, bpm)
rest(0.509, bpm)
keypress("d", x, bpm)
rest(0.509, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("8", x, bpm)
rest(0.509, bpm)
keypress("d", x, bpm)
rest(0.509, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.509, bpm)
keypress("o", x, bpm)
rest(0.509, bpm)
keypress("o", x, bpm)
rest(0.509, bpm)
keypress("p", x, bpm)
rest(0.509, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.509, bpm)
keypress("d", x, bpm)
rest(0.509, bpm)
keypress("s", x, bpm)
rest(0.491, bpm)
keypress("a", x, bpm)
rest(0.491, bpm)
keypress("p", x, bpm)
rest(1.019, bpm)
keypress("p", x, bpm)
rest(1.019, bpm)
keypress("O", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(1.019, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.509, bpm)
keypress("f", x, bpm)
rest(0.509, bpm)
keypress("d", x, bpm)
rest(0.509, bpm)
keypress("d", x, bpm)
rest(0.509, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
rest(0.509, bpm)
keypress("u", x, bpm)
rest(0.509, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
rest(1.519, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
rest(0.509, bpm)
keypress("u", x, bpm)
rest(1.009, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("9", x, bpm)
rest(0.255, bpm)
keypress("u", x, bpm)
rest(0.255, bpm)
keypress("u", x, bpm)
rest(0.509, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("9", x, bpm)
rest(0.509, bpm)
keypress("u", x, bpm)
rest(1.009, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
rest(1.528, bpm)
keypress("u", x, bpm)
rest(0.255, bpm)
keypress("u", x, bpm)
rest(0.255, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(1.009, bpm)
keypress("u", x, bpm)
rest(0.255, bpm)
keypress("u", x, bpm)
rest(0.255, bpm)
keypress("u", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("9", x, bpm)
rest(0.519, bpm)
keypress("u", x, bpm)
rest(1.519, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
rest(1.528, bpm)
keypress("y", x, bpm)
rest(0.245, bpm)
keypress("y", x, bpm)
rest(0.245, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(1.019, bpm)
keypress("9", x, bpm)
rest(1.269, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.509, bpm)
keypress("d", x, bpm)
rest(0.509, bpm)
keypress("a", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
rest(1.528, bpm)
keypress("y", x, bpm)
rest(0.245, bpm)
keypress("y", x, bpm)
rest(0.245, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
rest(0.509, bpm)
keypress("p", x, bpm)
rest(0.509, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
rest(1.509, bpm)
keypress("y", x, bpm)
rest(0.245, bpm)
keypress("u", x, bpm)
rest(0.245, bpm)
keypress("I", x, bpm)
rest(0.778, bpm)
keypress("u", x, bpm)
rest(0.259, bpm)
keypress("y", x, bpm)
rest(0.75, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("6", x, bpm)
rest(0.255, bpm)
keypress("a", x, bpm)
rest(0.255, bpm)
keypress("a", x, bpm)
rest(0.509, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.255, bpm)
keypress("p", x, bpm)
rest(0.255, bpm)
keypress("o", x, bpm)
rest(0.509, bpm)
keypress("o", x, bpm)
rest(1.019, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.255, bpm)
keypress("o", x, bpm)
rest(0.255, bpm)
keypress("p", x, bpm)
rest(0.255, bpm)
keypress("o", x, bpm)
rest(0.255, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(1.019, bpm)
keypress("o", x, bpm)
keypress("6", x, bpm)
rest(0.255, bpm)
keypress("o", x, bpm)
rest(0.255, bpm)
keypress("o", x, bpm)
rest(0.509, bpm)
keypress("o", x, bpm)
rest(0.245, bpm)
keypress("I", x, bpm)
rest(0.245, bpm)
keypress("o", x, bpm)
rest(0.245, bpm)
keypress("I", x, bpm)
rest(0.245, bpm)
keypress("o", x, bpm)
rest(0.255, bpm)
keypress("I", x, bpm)
rest(0.255, bpm)
keypress("u", x, bpm)
rest(0.509, bpm)
keypress("u", x, bpm)
rest(0.509, bpm)
keypress("Y", x, bpm)
rest(0.509, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(1.019, bpm)
keypress("u", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("9", x, bpm)
rest(1.019, bpm)
keypress("a", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
rest(0.509, bpm)
keypress("d", x, bpm)
rest(0.509, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.509, bpm)
keypress("a", x, bpm)
rest(0.509, bpm)
keypress("s", x, bpm)
keypress("9", x, bpm)
rest(0.509, bpm)
keypress("a", x, bpm)
rest(0.509, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("9", x, bpm)
rest(0.509, bpm)
keypress("y", x, bpm)
rest(0.509, bpm)
keypress("y", x, bpm)
rest(0.509, bpm)
keypress("y", x, bpm)
rest(0.509, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
rest(0.519, bpm)
keypress("p", x, bpm)
rest(0.519, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.509, bpm)
keypress("I", x, bpm)
rest(0.509, bpm)
keypress("I", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.519, bpm)
keypress("p", x, bpm)
rest(0.259, bpm)
keypress("p", x, bpm)
rest(0.259, bpm)
keypress("p", x, bpm)
rest(0.491, bpm)
keypress("o", x, bpm)
rest(1.269, bpm)
keypress("r", x, bpm)
rest(0.259, bpm)
keypress("I", x, bpm)
keypress("0", x, bpm)
rest(0.255, bpm)
keypress("I", x, bpm)
rest(0.255, bpm)
keypress("I", x, bpm)
rest(0.255, bpm)
keypress("I", x, bpm)
rest(0.255, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.519, bpm)
keypress("y", x, bpm)
rest(1.5, bpm)
keypress("6", x, bpm)
rest(0.509, bpm)
keypress("d", x, bpm)
rest(0.509, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
rest(0.509, bpm)
keypress("p", x, bpm)
rest(1.009, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("9", x, bpm)
rest(0.255, bpm)
keypress("p", x, bpm)
rest(0.255, bpm)
keypress("a", x, bpm)
rest(0.509, bpm)
keypress("a", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("9", x, bpm)
rest(2.019, bpm)
keypress("a", x, bpm)
keypress("8", x, bpm)
rest(0.509, bpm)
keypress("d", x, bpm)
rest(0.509, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.509, bpm)
keypress("o", x, bpm)
rest(0.509, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.509, bpm)
keypress("d", x, bpm)
rest(0.509, bpm)
keypress("s", x, bpm)
rest(0.509, bpm)
keypress("a", x, bpm)
rest(0.509, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
rest(1.019, bpm)
keypress("O", x, bpm)
keypress("0", x, bpm)
rest(0.245, bpm)
keypress("p", x, bpm)
rest(0.245, bpm)
keypress("a", x, bpm)
rest(1.009, bpm)
keypress("O", x, bpm)
rest(0.259, bpm)
keypress("p", x, bpm)
rest(0.259, bpm)
keypress("a", x, bpm)
rest(0.981, bpm)
keypress("u", x, bpm)
rest(1.037, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.509, bpm)
keypress("f", x, bpm)
rest(0.509, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(1.019, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("8", x, bpm)
rest(0.509, bpm)
keypress("d", x, bpm)
rest(0.509, bpm)
keypress("s", x, bpm)
rest(0.509, bpm)
keypress("a", x, bpm)
rest(0.509, bpm)
keypress("p", x, bpm)
rest(0.491, bpm)
keypress("o", x, bpm)
rest(0.491, bpm)
keypress("o", x, bpm)
rest(0.519, bpm)
keypress("p", x, bpm)
rest(0.519, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
rest(1.019, bpm)
keypress("O", x, bpm)
keypress("0", x, bpm)
rest(0.255, bpm)
keypress("p", x, bpm)
rest(0.255, bpm)
keypress("a", x, bpm)
rest(1.019, bpm)
keypress("O", x, bpm)
rest(0.255, bpm)
keypress("p", x, bpm)
rest(0.255, bpm)
keypress("a", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.509, bpm)
keypress("f", x, bpm)
rest(0.509, bpm)
keypress("d", x, bpm)
rest(0.509, bpm)
keypress("d", x, bpm)
rest(0.509, bpm)
keypress("s", x, bpm)
rest(0.981, bpm)
keypress("y", x, bpm)
rest(1.037, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(1.019, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
rest(0.259, bpm)
keypress("y", x, bpm)
rest(0.259, bpm)
keypress("u", x, bpm)
rest(1.019, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
rest(1.019, bpm)
keypress("y", x, bpm)
rest(0.255, bpm)
keypress("y", x, bpm)
rest(0.255, bpm)
keypress("u", x, bpm)
rest(1.009, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
rest(1.019, bpm)
keypress("a", x, bpm)
keypress("9", x, bpm)
rest(0.509, bpm)
keypress("a", x, bpm)
rest(0.509, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("9", x, bpm)
rest(0.509, bpm)
keypress("I", x, bpm)
rest(0.509, bpm)
keypress("d", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("0", x, bpm)
rest(0.259, bpm)
keypress("y", x, bpm)
rest(0.259, bpm)
keypress("u", x, bpm)
rest(1.019, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
rest(0.255, bpm)
keypress("y", x, bpm)
rest(0.255, bpm)
keypress("y", x, bpm)
rest(0.509, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(1.019, bpm)
keypress("y", x, bpm)
rest(1.019, bpm)
keypress("y", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(1.009, bpm)
keypress("y", x, bpm)
rest(0.255, bpm)
keypress("y", x, bpm)
rest(0.255, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
rest(1.019, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.509, bpm)
keypress("p", x, bpm)
rest(0.509, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(1.037, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(1.009, bpm)
keypress("u", x, bpm)
rest(0.509, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
rest(1.519, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
rest(0.509, bpm)
keypress("u", x, bpm)
rest(1.009, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("9", x, bpm)
rest(0.255, bpm)
keypress("I", x, bpm)
rest(0.255, bpm)
keypress("I", x, bpm)
rest(0.509, bpm)
keypress("I", x, bpm)
rest(0.509, bpm)
keypress("I", x, bpm)
rest(0.255, bpm)
keypress("o", x, bpm)
rest(0.255, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.509, bpm)
keypress("y", x, bpm)
rest(1.009, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("0", x, bpm)
rest(0.509, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
rest(0.245, bpm)
keypress("u", x, bpm)
rest(0.245, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
rest(0.509, bpm)
keypress("u", x, bpm)
rest(1.019, bpm)
keypress("u", x, bpm)
rest(0.255, bpm)
keypress("u", x, bpm)
rest(0.255, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.509, bpm)
keypress("o", x, bpm)
rest(0.255, bpm)
keypress("I", x, bpm)
rest(0.255, bpm)
keypress("I", x, bpm)
keypress("9", x, bpm)
rest(0.509, bpm)
keypress("I", x, bpm)
rest(1.509, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.509, bpm)
keypress("p", x, bpm)
rest(0.509, bpm)
keypress("0", x, bpm)
rest(1.019, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(2.019, bpm)
keypress("I", x, bpm)
keypress("9", x, bpm)
rest(0.509, bpm)
keypress("I", x, bpm)
rest(0.255, bpm)
keypress("o", x, bpm)
rest(0.255, bpm)
keypress("p", x, bpm)
rest(0.509, bpm)
keypress("y", x, bpm)
rest(0.509, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.509, bpm)
keypress("u", x, bpm)
rest(0.509, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(0.509, bpm)
keypress("I", x, bpm)
rest(0.255, bpm)
keypress("I", x, bpm)
rest(0.255, bpm)
keypress("I", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.509, bpm)
keypress("I", x, bpm)
rest(0.255, bpm)
keypress("o", x, bpm)
rest(0.255, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.509, bpm)
keypress("y", x, bpm)
rest(3.028, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.255, bpm)
keypress("u", x, bpm)
rest(0.255, bpm)
keypress("u", x, bpm)
rest(0.509, bpm)
keypress("u", x, bpm)
rest(0.509, bpm)
keypress("u", x, bpm)
rest(0.255, bpm)
keypress("u", x, bpm)
rest(0.255, bpm)
keypress("u", x, bpm)
rest(0.509, bpm)
keypress("u", x, bpm)

finishedSong()
