local translator = {}

local translations = {
    ["play song"] = "Tocar!",
    ["search"] = "procurar...",
    ["songname"] = "NOME DA MÚSICA",
    ["toggle ui"] = "alternar ui",
    ["spoof midi"] = "falsificar midi",
    ["shuffle play songs"] = "EMBARALHAR MÚSICAS",
    ["play random song"] = "MÚSICA ALEATÓRIA",
    ["new"] = "novas",
    ["peak"] = "top",
    ["best"] = "melhores",
    ["epic"] = "épico",
    ["beautiful"] = "bonitas",
    ["video games"] = "videogames",
    ["movies/tv"] = "filmes/tv",
    ["memes"] = "memes",
    ["classical"] = "clássicas",
    ["pop/hiphop"] = "pop/hiphop",
    ["anime/jpop"] = "anime/jpop",
    ["sad"] = "tristes",
    ["electronic"] = "eletrônicas",
    ["rock"] = "rock",
    ["creepy/weirdcore"] = "assustador/weirdcore",
    ["unsupported executor"] = "Seu executor pode não suportar este recurso.",
    ["custom songs"] = "músicas custom",
    ["favourites"] = "favoritas",
    ["other"] = "outros",
    ["all"] = "todas",
    ["songplayingerror"] = "Uma música já está sendo reproduzida.",
    ["stoploopingsongs"] = "PARAR LOOP MÚSICAS",
    ["midispoofon"] = "A falsificação de MIDI está ativada. Clique no ponto de interrogação para mais informações.",
    ["midispoofoff"] = "A falsificação de MIDI está desativada.",
    ["beganplayingnotif"] = "Começou a tocar a música.",
    ["brokensongscript"] = "Seu script de música está quebrado. Se estiver confuso, entre em contato com o suporte no Discord.",
    ["doubleclickdelete"] = "Clique duas vezes para excluir a música.",
    ["songdeleted"] = "Sua música foi excluída.",
    ["spoof midi title"] = "falsificar midi: o que é?",
    ["spoof midi info"] = "Esta opção aparece porque você está no jogo 'piano rooms'. Quando 'falsificar midi' está LIGADO, lucigui diz ao jogo que seus inputs vêm de um teclado MIDI real, não de um QWERTY! Isso faz o autoplay parecer mais real. Basta ativar e tocar qualquer música!",
    ["midi connect reminder"] = "Não esqueça de ativar o midi connect!",
    ["custom song instructions"] = "Converta um arquivo MIDI em script usando MIDI2LUA (bit.ly/midi2lua). Depois, cole o script completo aqui para adicionar a música no lucigui!",
    ["insert song script"] = "Insira o script e o nome da sua música.",
    ["song name prompt"] = "Qual o nome da sua música?",
    ["submit"] = "ENVIAR!",
    ["songnameexists"] = "Você já tem uma música com esse nome.",
    ["songadded"] = "Você adicionou a música \"%s\".",
    ["copy"] = "copiar!",
    ["help info"] = "Precisa de ajuda com lucigui? Quer transformar arquivos MIDI em scripts de autoplay, encontrar tutoriais ou obter ajuda no Discord? Clique no botão abaixo para copiar o link do site oficial!",
    ["resources"] = "recursos",
    ["nevermind"] = "deixa pra lá",
    ["linkcopied"] = "https://hellohellohell0.com foi copiado para sua área de transferência!",
    ["error margin"] = "margem de erro: ",
    ["what language"] = "qual idioma você fala?",
    ["confirm"] = "confirmar",
    ["stopping..."] = "parando...",
    ["songfinished"] = "sua música terminou.",
    ["invalidbpm"] = "por favor, coloque um bpm válido",
    ["copykey"] = "COPIAR LINK DA CHAVE",
    ["keytitle"] = "lucigui requer uma chave para usar. Siga as instruções abaixo.",
    ["keyinsert"] = "cole a chave aqui (exemplo: 0491)",
    ["step1"] = "Passo 1:",
    ["step2"] = "Passo 2:",
    ["step3"] = "Passo 3:",
    ["copykeysite"] = "Clique no botão para copiar o link do site da chave.",
    ["completetaskforkey"] = "Conclua a tarefa no site para obter a chave.",
    ["pastekeyhere"] = "Cole a chave aqui →",
    ["submitkey"] = "Enviar chave!",
    ["keylinkcopied"] = "O link da chave foi copiado para sua área de transferência.",
    ["keyempty"] = "O campo da chave está vazio. Leia as instruções para obter a chave.",
    ["keysuccess"] = "Sucesso.",
    ["keyinvalid"] = "Sua chave é inválida. Se precisar de ajuda, entre no servidor do Discord clicando no botão de interrogação.",
    ["keyexpired"] = "Esta chave expirou. A chave foi redefinida recentemente. Refaça as tarefas no site da chave para obter uma nova chave.",
    ["categories"] = "categorias",
    ["utilities"] = "ferramentas"
}

function translator:translateText(text)
    return translations[text] or text
end

function translator:requestLang(frame, type)
    -- Não faz nada, sempre usa português
end

return translator
